version: '3'

services:
    client:
        build: ./
        ports:
            - 3000:3000
        command: yarn start
        volumes:
            - ./src:/app/src
            - ./public:/app/public